services:
  nestjs_app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_mail_server
    restart: on-failure
    ports:
      - 3081:3000
    environment:
      - SERVER_NAME="Mail Server"
      - PORT=3081
      - NODE_ENV="development"
    env_file:
      - .env.development
    networks:
      - my-network

networks:
  my-network:
    external: true
  # nestjs_network:
  # driver: bridge
  # ipam:
  #   config:
  #     - subnet: 192.168.1.0/24
  #       gateway: 192.168.1.1

volumes:
  nestjsdbdata:
    driver: local
